[package]
name = "rust-client"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
gloo-timers = {version = "0.3.0", features = ["futures"]}
log = "0.4.27"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
wasm-logger = "0.2.0"

[dev-dependencies]
env_logger = "0.11.8"

[lib]
crate-type = ["cdylib"]
