[package]
name = "random"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
wasm-bindgen = "0.2.100"
wasm-logger = "0.2.0"

[dev-dependencies]
env_logger = "0.11.8"

[lib]
crate-type = ["cdylib"]
